### ISSUE TITLE
Suggestion: Use Cabal's file searching 

### ISSUE THREAD

**Issue by googleson78** [spinda/liquidhaskell-cabal#14]
It seems like `liquidhaskell-cabal` could use [findModuleFiles](http://hackage.haskell.org/package/Cabal-2.4.1.0/docs/Distribution-Simple-Utils.html#v:findModuleFiles) instead of implementing its own `find*Sources`.

I am willing to do a PR, if this is fine.

**Comment by spinda** [comment]
I don't think this would work.

We need to find not just `.hs`/`.lhs` files corresponding to a component's modules, but `.hs-boot`/`.lhs-boot` files as well, if they exist. Grouping them all together and passing `["hs", "lhs", "hs-boot", "lhs-boot"]` as the extension list for `findModuleFiles` wouldn't work, as the search would stop as soon as a module's `.hs` file is found, ignoring a `.hs-boot` file if a corresponding one exists.

Therefore, we need to do two passes to locate all the module files: one passing `["hs", "lhs"]` and one passing `["hs-boot", "lhs-boot"]`. Unfortunately, `findModuleFile` calls `die` if no module file matching one of the given extensions is found, so the second pass would terminate the program unless every module has a matching `.hs-boot`/`.lhs-boot` file. Contrast this with `findModuleSource` in `liquidhaskell-cabal`, which returns `Nothing` if a matching file isn't found.
