### ISSUE TITLE
Inaccurate version bounds 

### ISSUE THREAD

**Issue by hvr** [spinda/liquidhaskell-cabal#15]
As can be seen at https://matrix.hackage.haskell.org/package/liquidhaskell-cabal@1559177069 there's several red cells which denote inaccurate version bounds.

I haven't had time yet to investigate, but it looks like the omission of version bounds on the `directory` and `Cabal` dependencies are the likely culprit.

Note that uploading a new release is not going to address the issue at hand: the metadata for the affected releases can fixed up via Hackage's WebUI, e.g. at

- https://hackage.haskell.org/package/liquidhaskell-cabal-0.2.1.0/liquidhaskell-cabal.cabal/edit
- https://hackage.haskell.org/package/liquidhaskell-cabal-0.2.0.0/liquidhaskell-cabal.cabal/edit
- https://hackage.haskell.org/package/liquidhaskell-cabal-0.1.1.0/liquidhaskell-cabal.cabal/edit
- https://hackage.haskell.org/package/liquidhaskell-cabal-0.1.0.0/liquidhaskell-cabal.cabal/edit

**Comment by spinda** [comment]
Thanks for the report. I probably won't have time to dig into this myself until the weekend, though. Is it urgent?

**Comment by hvr** [comment]
I looked a into this and performed respective revisions to have the metadata reflect reality more accuralety:

 - https://hackage.haskell.org/package/liquidhaskell-cabal-0.1.0.0/revisions/
 - https://hackage.haskell.org/package/liquidhaskell-cabal-0.1.1.0/revisions/
 - https://hackage.haskell.org/package/liquidhaskell-cabal-0.2.0.0/revisions/
 - https://hackage.haskell.org/package/liquidhaskell-cabal-0.2.1.0/revisions/

and this resulted in the new situation below:

https://matrix.hackage.haskell.org/package/liquidhaskell-cabal@1559345206

**Comment by spinda** [comment]
Thank you for the assistance!
